ARG python_image=python
ARG python_image_tag=3.7-slim-buster

# Base off the community Python image
FROM ${python_image}:${python_image_tag}

RUN apt-get update && apt-get install -y --no-install-recommends \
	build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /application

COPY ./server/requirements.txt .
COPY ./server/requirements-dev.txt .
ARG pip_install_args
RUN pip install $pip_install_args --no-cache-dir -r requirements.txt -r requirements-dev.txt

# Add source files and pre-compile them
COPY ./server/ /application

RUN python -m compileall -f
RUN python -m compileall -f .

USER $USER

EXPOSE 5050

CMD ["gunicorn", "--config", "gunicorn.conf", "pubs_ui:app"]