crossref_200_ok = {u'message': {u'DOI': u'10.1002/ecy.1625',
              u'ISSN': [u'0012-9658'],
              u'URL': u'http://dx.doi.org/10.1002/ecy.1625',
              u'archive': [u'Portico'],
              u'author': [{u'affiliation': [{u'name': u'U.S. Geological Survey; 700 Cajundome Blvd. Lafayette Louisiana 70506 USA'}],
                           u'family': u'Osland',
                           u'given': u'Michael J.'},
                          {u'affiliation': [{u'name': u'U.S. Geological Survey; 700 Cajundome Blvd. Lafayette Louisiana 70506 USA'}],
                           u'family': u'Day',
                           u'given': u'Richard H.'},
                          {u'affiliation': [{u'name': u'U.S. Geological Survey; 700 Cajundome Blvd. Lafayette Louisiana 70506 USA'}],
                           u'family': u'Hall',
                           u'given': u'Courtney T.'},
                          {u'affiliation': [{u'name': u'University of Oklahoma; Norman Oklahoma 73019-0390 USA'}],
                           u'family': u'Brumfield',
                           u'given': u'Marisa D.'},
                          {u'affiliation': [{u'name': u'U.S. Geological Survey; 700 Cajundome Blvd. Lafayette Louisiana 70506 USA'}],
                           u'family': u'Dugas',
                           u'given': u'Jason L.'},
                          {u'affiliation': [{u'name': u'U.S. Geological Survey; 700 Cajundome Blvd. Lafayette Louisiana 70506 USA'}],
                           u'family': u'Jones',
                           u'given': u'William R.'}],
              u'container-title': [u'Ecology'],
              u'content-domain': {u'crossmark-restriction': False,
                                  u'domain': []},
              u'created': {u'date-parts': [[2016, 10, 17]],
                           u'date-time': u'2016-10-17T13:33:09Z',
                           u'timestamp': 1476711189000},
              u'deposited': {u'date-parts': [[2017, 6, 15]],
                             u'date-time': u'2017-06-15T01:27:37Z',
                             u'timestamp': 1497490057000},
              u'funder': [{u'DOI': u'10.13039/100000203',
                           u'award': [],
                           u'doi-asserted-by': u'publisher',
                           u'name': u'U.S. Geological Survey'},
                          {u'DOI': u'10.13039/501100001589',
                           u'award': [],
                           u'doi-asserted-by': u'publisher',
                           u'name': u'Environmental Protection Agency'},
                          {u'award': [],
                           u'name': u'Department of Interior Southeast Climate Science Center'},
                          {u'award': [],
                           u'name': u'Department of Interior South Central Climate Science Center'},
                          {u'award': [],
                           u'name': u'Southern Climate Impacts Planning Program'}],
              u'indexed': {u'date-parts': [[2017, 10, 5]],
                           u'date-time': u'2017-10-05T13:42:23Z',
                           u'timestamp': 1507210943579},
              u'is-referenced-by-count': 10,
              u'issn-type': [{u'type': u'print', u'value': u'0012-9658'}],
              u'issue': u'1',
              u'issued': {u'date-parts': [[2016, 12, 9]]},
              u'license': [{u'URL': u'http://doi.wiley.com/10.1002/tdm_license_1',
                            u'content-version': u'tdm',
                            u'delay-in-days': 0,
                            u'start': {u'date-parts': [[2016, 12, 9]],
                                       u'date-time': u'2016-12-09T00:00:00Z',
                                       u'timestamp': 1481241600000}},
                           {u'URL': u'http://onlinelibrary.wiley.com/termsAndConditions',
                            u'content-version': u'am',
                            u'delay-in-days': 365,
                            u'start': {u'date-parts': [[2017, 12, 9]],
                                       u'date-time': u'2017-12-09T00:00:00Z',
                                       u'timestamp': 1512777600000}},
                           {u'URL': u'http://onlinelibrary.wiley.com/termsAndConditions',
                            u'content-version': u'vor',
                            u'delay-in-days': 0,
                            u'start': {u'date-parts': [[2016, 12, 9]],
                                       u'date-time': u'2016-12-09T00:00:00Z',
                                       u'timestamp': 1481241600000}}],
              u'link': [{u'URL': u'https://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fecy.1625',
                         u'content-type': u'application/pdf',
                         u'content-version': u'vor',
                         u'intended-application': u'text-mining'},
                        {u'URL': u'https://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fecy.1625',
                         u'content-type': u'unspecified',
                         u'content-version': u'vor',
                         u'intended-application': u'text-mining'},
                        {u'URL': u'http://api.wiley.com/onlinelibrary/chorus/v1/articles/10.1002%2Fecy.1625',
                         u'content-type': u'application/pdf',
                         u'content-version': u'am',
                         u'intended-application': u'syndication'},
                        {u'URL': u'http://onlinelibrary.wiley.com/wol1/doi/10.1002/ecy.1625/fullpdf',
                         u'content-type': u'unspecified',
                         u'content-version': u'vor',
                         u'intended-application': u'similarity-checking'}],
              u'member': u'311',
              u'original-title': [],
              u'page': u'125-137',
              u'prefix': u'10.1002',
              u'published-online': {u'date-parts': [[2016, 12, 9]]},
              u'published-print': {u'date-parts': [[2017, 1]]},
              u'publisher': u'Wiley-Blackwell',
              u'reference': [{u'author': u'Ackerman',
                              u'first-page': u'223',
                              u'key': u'10.1002/ecy.1625-BIB0001|ecy1625-cit-0001',
                              u'volume-title': u'Population biology of the Florida manatee. Information and technology report 1',
                              u'year': u'1995'},
                             {u'DOI': u'10.1017/CBO9780511565328',
                              u'author': u'Adam',
                              u'doi-asserted-by': u'crossref',
                              u'key': u'10.1002/ecy.1625-BIB0002|ecy1625-cit-0002',
                              u'volume-title': u'Saltmarsh ecology',
                              u'year': u'1990'},
                             {u'DOI': u'10.1016/j.foreco.2009.09.001',
                              u'article-title': u'A global overview of drought and heat-induced tree mortality reveals emerging climate change risks for forests',
                              u'author': u'Allen',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'660',
                              u'journal-title': u'Forest Ecology and Management',
                              u'key': u'10.1002/ecy.1625-BIB0003|ecy1625-cit-0003',
                              u'volume': u'259',
                              u'year': u'2010'},
                             {u'author': u'Alongi',
                              u'key': u'10.1002/ecy.1625-BIB0004|ecy1625-cit-0004',
                              u'volume-title': u'The energetics of mangrove forests',
                              u'year': u'2009'},
                             {u'DOI': u'10.1007/s40641-015-0002-x',
                              u'article-title': u'The impact of climate change on mangrove forests',
                              u'author': u'Alongi',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'30',
                              u'journal-title': u'Current Climate Change Reports',
                              u'key': u'10.1002/ecy.1625-BIB0005|ecy1625-cit-0005',
                              u'volume': u'1',
                              u'year': u'2015'},
                             {u'DOI': u'10.1371/journal.pone.0125404',
                              u'article-title': u'The contribution of mangrove expansion to salt marsh loss on the Texas Gulf Coast',
                              u'author': u'Armitage',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e0125404',
                              u'journal-title': u'PLoS ONE',
                              u'key': u'10.1002/ecy.1625-BIB0006|ecy1625-cit-0006',
                              u'volume': u'10',
                              u'year': u'2015'},
                             {u'DOI': u'10.1016/j.ecss.2012.12.007',
                              u'article-title': u'Historical reconstruction of mangrove expansion in the Gulf of Mexico: linking climate change with carbon sequestration in coastal wetlands',
                              u'author': u'Bianchi',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'7',
                              u'journal-title': u'Estuarine, Coastal and Shelf Science',
                              u'key': u'10.1002/ecy.1625-BIB0007|ecy1625-cit-0007',
                              u'volume': u'119',
                              u'year': u'2013'},
                             {u'DOI': u'10.1111/gcb.12574',
                              u'article-title': u'Climate extremes drive changes in functional community structure',
                              u'author': u'Boucek',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1821',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0008|ecy1625-cit-0008',
                              u'volume': u'20',
                              u'year': u'2014'},
                             {u'DOI': u'10.1002/ecs2.1455',
                              u'article-title': u'A\xa0review of subtropical community resistance and resilience\xa0to extreme cold spells',
                              u'author': u'Boucek',
                              u'doi-asserted-by': u'publisher',
                              u'first-page': u'e01455',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0009|ecy1625-cit-0009',
                              u'volume': u'7'},
                             {u'DOI': u'10.1007/s13157-016-0793-0',
                              u'article-title': u'Allometric models for estimating aboveground biomass, carbon and nitrogen stocks in temperate Avicennia marina',
                              u'author': u'Bulmer',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'841',
                              u'journal-title': u'Wetlands',
                              u'key': u'10.1002/ecy.1625-BIB0010|ecy1625-cit-0010',
                              u'volume': u'36',
                              u'year': u'2016'},
                             {u'DOI': u'10.1073/pnas.1315800111',
                              u'article-title': u'Poleward expansion of mangroves is a threshold response to decreased frequency of extreme cold events',
                              u'author': u'Cavanaugh',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'723',
                              u'journal-title': u'Proceedings of the National Academy of Sciences',
                              u'key': u'10.1002/ecy.1625-BIB0011|ecy1625-cit-0011',
                              u'volume': u'111',
                              u'year': u'2014'},
                             {u'DOI': u'10.1111/gcb.12843',
                              u'article-title': u"Integrating physiological threshold experiments with climate modeling to project mangrove species' range expansion",
                              u'author': u'Cavanaugh',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1928',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0012|ecy1625-cit-0012',
                              u'volume': u'21',
                              u'year': u'2015'},
                             {u'DOI': u'10.1029/CE041p0225',
                              u'author': u'Clough',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'225',
                              u'key': u'10.1002/ecy.1625-BIB0013|ecy1625-cit-0013',
                              u'volume-title': u'Tropical mangrove ecosystems',
                              u'year': u'1992'},
                             {u'DOI': u'10.1111/1365-2435.12443',
                              u'article-title': u'Convergence of three mangrove species towards freeze-tolerant phenotypes at an expanding range edge',
                              u'author': u'Cook-Patton',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1332',
                              u'journal-title': u'Functional Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0014|ecy1625-cit-0014',
                              u'volume': u'29',
                              u'year': u'2015'},
                             {u'key': u'10.1002/ecy.1625-BIB0015|ecy1625-cit-0015',
                              u'unstructured': u'Couvillion , B. R. J. A. Barras G. D. Steyer W. Sleavin M. \xa0 Fischer H. Beck N. Trahan B. Griffin D. Heckman 2011 Land area change in coastal Louisiana from 1932 to 2010: U.S. Geological Survey Scientific Investigations Map 3164, scale 1:265,000'},
                             {u'DOI': u'10.1002/joc.937',
                              u'article-title': u'Mapping the climate of Puerto Rico, Vieques and Culebra',
                              u'author': u'Daly',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1359',
                              u'journal-title': u'International Journal of Climatology',
                              u'key': u'10.1002/ecy.1625-BIB0016|ecy1625-cit-0016',
                              u'volume': u'23',
                              u'year': u'2003'},
                             {u'DOI': u'10.1002/joc.1688',
                              u'article-title': u'Physiographically sensitive mapping of climatological temperature and precipitation across the conterminous United States',
                              u'author': u'Daly',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'2031',
                              u'journal-title': u'International Journal of Climatology',
                              u'key': u'10.1002/ecy.1625-BIB0017|ecy1625-cit-0017',
                              u'volume': u'28',
                              u'year': u'2008'},
                             {u'DOI': u'10.1175/2010JAMC2536.1',
                              u'article-title': u'Development of a new USDA plant hardiness zone map for the United States',
                              u'author': u'Daly',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'242',
                              u'journal-title': u'Journal of Applied Meteorology and Climatology',
                              u'key': u'10.1002/ecy.1625-BIB0018|ecy1625-cit-0018',
                              u'volume': u'51',
                              u'year': u'2012'},
                             {u'DOI': u'10.1002/ece3.2270',
                              u'article-title': u'Precocious reproduction increases at the leading edge of a mangrove range expansion',
                              u'author': u'Dangremond',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'5087',
                              u'journal-title': u'Ecology and Evolution',
                              u'key': u'10.1002/ecy.1625-BIB0019|ecy1625-cit-0019',
                              u'volume': u'6',
                              u'year': u'2016'},
                             {u'article-title': u'The ecology and geologic role of mangroves in Florida. Carnegie Institute of Washington Publications',
                              u'author': u'Davis',
                              u'first-page': u'303',
                              u'journal-title': u'Papers from Tortugas Laboratory',
                              u'key': u'10.1002/ecy.1625-BIB0020|ecy1625-cit-0020',
                              u'volume': u'32',
                              u'year': u'1940'},
                             {u'DOI': u'10.1111/geb.12000',
                              u'article-title': u'Vegetation-microclimate feedbacks in woodland-grassland ecotones',
                              u'author': u"D'Odorico",
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'364',
                              u'journal-title': u'Global Ecology and Biogeography',
                              u'key': u'10.1002/ecy.1625-BIB0021|ecy1625-cit-0021',
                              u'volume': u'22',
                              u'year': u'2013'},
                             {u'DOI': u'10.1007/s12237-015-9993-8',
                              u'article-title': u'Mangrove range expansion rapidly increases coastal wetland carbon storage',
                              u'author': u'Doughty',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'385',
                              u'journal-title': u'Estuaries and Coasts',
                              u'key': u'10.1002/ecy.1625-BIB0022|ecy1625-cit-0022',
                              u'volume': u'39',
                              u'year': u'2016'},
                             {u'DOI': u'10.1002/ecs2.1302',
                              u'article-title': u'Differential impacts from an extreme cold spell on subtropical vs. tropical specialist bees in southern Florida',
                              u'author': u'Downing',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e01302',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0023|ecy1625-cit-0023',
                              u'volume': u'7',
                              u'year': u'2016'},
                             {u'DOI': u'10.1126/science.289.5487.2068',
                              u'article-title': u'Climate extremes: observations, modeling, and impacts',
                              u'author': u'Easterling',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'2068',
                              u'journal-title': u'Science',
                              u'key': u'10.1002/ecy.1625-BIB0024|ecy1625-cit-0024',
                              u'volume': u'289',
                              u'year': u'2000'},
                             {u'article-title': u'Integration of remote sensing and spatial information technologies for mapping black mangrove on the Texas gulf coast',
                              u'author': u'Everitt',
                              u'first-page': u'64',
                              u'journal-title': u'Journal of Coastal Research',
                              u'key': u'10.1002/ecy.1625-BIB0025|ecy1625-cit-0025',
                              u'volume': u'12',
                              u'year': u'1996'},
                             {u'article-title': u'Macroclimatic change expected to transform coastal wetland ecosystems this century',
                              u'author': u'Gabler',
                              u'journal-title': u'Nature Climate Change',
                              u'key': u'10.1002/ecy.1625-BIB0026|ecy1625-cit-0026'},
                             {u'DOI': u'10.1098/rspb.2008.1480',
                              u'article-title': u'Geographic range limits: achieving synthesis',
                              u'author': u'Gaston',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1395',
                              u'journal-title': u'Proceedings of the Royal Society of London B: Biological Sciences',
                              u'key': u'10.1002/ecy.1625-BIB0027|ecy1625-cit-0027',
                              u'volume': u'276',
                              u'year': u'2009'},
                             {u'DOI': u'10.1073/pnas.1400687111',
                              u'article-title': u'Mangrove reemergence in the northernmost range limit of eastern Florida',
                              u'author': u'Giri',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'E1447',
                              u'journal-title': u'Proceedings of the National Academy of Sciences',
                              u'key': u'10.1002/ecy.1625-BIB0028|ecy1625-cit-0028',
                              u'volume': u'111',
                              u'year': u'2014'},
                             {u'DOI': u'10.2112/JCOASTRES-D-11-00028.1',
                              u'article-title': u"Mapping and monitoring Louisiana's mangroves in the aftermath of the 2010 Gulf of Mexico oil spill",
                              u'author': u'Giri',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1059',
                              u'journal-title': u'Journal of Coastal Research',
                              u'key': u'10.1002/ecy.1625-BIB0029|ecy1625-cit-0029',
                              u'volume': u'27',
                              u'year': u'2011'},
                             {u'article-title': u"On the evolutionary ecology of species' ranges",
                              u'author': u'Holt',
                              u'first-page': u'159',
                              u'journal-title': u'Evolutionary Ecology Research',
                              u'key': u'10.1002/ecy.1625-BIB0030|ecy1625-cit-0030',
                              u'volume': u'5',
                              u'year': u'2003'},
                             {u'DOI': u'10.1890/13-2186.1',
                              u'article-title': u'Resistance and resilience of a grassland ecosystem to climate extremes',
                              u'author': u'Hoover',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'2646',
                              u'journal-title': u'Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0031|ecy1625-cit-0031',
                              u'volume': u'95',
                              u'year': u'2014'},
                             {u'DOI': u'10.1002/9781118412787.ch6',
                              u'author': u'Ib\xe1\xf1ez',
                              u'doi-asserted-by': u'crossref',
                              u'edition': u'2',
                              u'first-page': u'129',
                              u'key': u'10.1002/ecy.1625-BIB0032|ecy1625-cit-0032',
                              u'volume-title': u'Estuarine ecology',
                              u'year': u'2012'},
                             {u'author': u'IPCC',
                              u'key': u'10.1002/ecy.1625-BIB0033|ecy1625-cit-0033',
                              u'volume-title': u'Climate change 2013: the physical science basis. Contribution of working group I to the fifth assessment report of the intergovernmental panel on climate change',
                              u'year': u'2013'},
                             {u'DOI': u'10.1016/j.crte.2008.07.002',
                              u'article-title': u'Research frontiers in climate change: effects of extreme meteorological events on ecosystems',
                              u'author': u'Jentsch',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'621',
                              u'journal-title': u'Comptes Rendus Geoscience',
                              u'key': u'10.1002/ecy.1625-BIB0034|ecy1625-cit-0034',
                              u'volume': u'340',
                              u'year': u'2008'},
                             {u'DOI': u'10.1890/1540-9295(2007)5[365:ANGOCE]2.0.CO;2',
                              u'article-title': u'A new generation of climate-change experiments: events, not trends',
                              u'author': u'Jentsch',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'365',
                              u'journal-title': u'Frontiers in Ecology and the Environment',
                              u'key': u'10.1002/ecy.1625-BIB0035|ecy1625-cit-0035',
                              u'volume': u'5',
                              u'year': u'2007'},
                             {u'DOI': u'10.1016/j.ecolmodel.2015.04.013',
                              u'article-title': u'Defining the next generation modeling of coastal ecotone dynamics in response to global change',
                              u'author': u'Jiang',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'168',
                              u'journal-title': u'Ecological Modelling',
                              u'key': u'10.1002/ecy.1625-BIB0036|ecy1625-cit-0036',
                              u'volume': u'326',
                              u'year': u'2016'},
                             {u'DOI': u'10.1111/jbi.12813',
                              u'article-title': u'Contrasting genetic effects of red mangrove (Rhizophora mangle L.) range expansion along West and East Florida',
                              u'author': u'Kennedy',
                              u'doi-asserted-by': u'publisher',
                              u'journal-title': u'Journal of Biogeography',
                              u'key': u'10.1002/ecy.1625-BIB0037|ecy1625-cit-0037'},
                             {u'DOI': u'10.1007/978-3-662-05214-3',
                              u'author': u'Larcher',
                              u'doi-asserted-by': u'crossref',
                              u'key': u'10.1002/ecy.1625-BIB0038|ecy1625-cit-0038',
                              u'volume-title': u'Physiological plant ecology: ecophysiology and stress physiology of functional groups',
                              u'year': u'2003'},
                             {u'DOI': u'10.1371/journal.pone.0023047',
                              u'article-title': u'Severe 2010 cold-water event caused unprecedented mortality to corals of the Florida reef tract and reversed previous survivorship patterns',
                              u'author': u'Lirman',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e23047',
                              u'journal-title': u'PLoS ONE',
                              u'key': u'10.1002/ecy.1625-BIB0039|ecy1625-cit-0039',
                              u'volume': u'6',
                              u'year': u'2011'},
                             {u'DOI': u'10.2307/3671923',
                              u'article-title': u'Comparison of the effects of the severe freezes of 1983 and 1989 on native woody plants in the Lower Rio Grande Valley, Texas',
                              u'author': u'Lonard',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'213',
                              u'journal-title': u'The Southwestern Naturalist',
                              u'key': u'10.1002/ecy.1625-BIB0040|ecy1625-cit-0040',
                              u'volume': u'36',
                              u'year': u'1991'},
                             {u'DOI': u'10.1007/978-3-319-27422-5_7',
                              u'author': u'Lovelock',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'149',
                              u'key': u'10.1002/ecy.1625-BIB0041|ecy1625-cit-0041',
                              u'volume-title': u'Tropical tree physiology: adaptations and responses in a changing environment',
                              u'year': u'2016'},
                             {u'article-title': u'The impact of low temperature stress on mangrove structure and growth',
                              u'author': u'Lugo',
                              u'first-page': u'149',
                              u'journal-title': u'Tropical Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0042|ecy1625-cit-0042',
                              u'volume': u'18',
                              u'year': u'1977'},
                             {u'author': u'MacArthur',
                              u'key': u'10.1002/ecy.1625-BIB0043|ecy1625-cit-0043',
                              u'volume-title': u'Geographical ecology: patterns in the distribution of species',
                              u'year': u'1972'},
                             {u'DOI': u'10.3389/fpls.2014.00503',
                              u'article-title': u'Avicennia germinans (black mangrove) vessel architecture is linked to chilling and salinity tolerance in the Gulf of Mexico',
                              u'author': u'Madrid',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'503',
                              u'journal-title': u'Frontiers in Plant Science',
                              u'key': u'10.1002/ecy.1625-BIB0044|ecy1625-cit-0044',
                              u'volume': u'5',
                              u'year': u'2014'},
                             {u'key': u'10.1002/ecy.1625-BIB0045|ecy1625-cit-0045',
                              u'unstructured': u'Martin , J. H. L. W. McEachron 1996 Historical annotated review of winter kills of marine organisms in Texas bays'},
                             {u'DOI': u'10.1002/ecs2.1439',
                              u'article-title': u'Large reptiles and cold temperatures: Do extreme cold spells set distributional limits for tropical reptiles in Florida?',
                              u'author': u'Mazzotti',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e01439',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0046|ecy1625-cit-0046',
                              u'volume': u'7',
                              u'year': u'2016'},
                             {u'key': u'10.1002/ecy.1625-BIB0047|ecy1625-cit-0047',
                              u'unstructured': u'Michot , T. C. R. H. Day C. J. Wells 2010 Increase in black mangrove abundance in coastal Louisiana'},
                             {u'author': u'Montagna',
                              u'edition': u'2',
                              u'first-page': u'96',
                              u'key': u'10.1002/ecy.1625-BIB0048|ecy1625-cit-0048',
                              u'volume-title': u'The impact of global warming on Texas',
                              u'year': u'2011'},
                             {u'article-title': u'Effects of freezes on tropical trees in Everglades National Park Florida, USA',
                              u'author': u'Olmsted',
                              u'first-page': u'17',
                              u'journal-title': u'Tropical Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0049|ecy1625-cit-0049',
                              u'volume': u'34',
                              u'year': u'1993'},
                             {u'DOI': u'10.1111/gcb.12126',
                              u'article-title': u'Winter climate change and coastal wetland foundation species: salt marshes vs. mangrove forests in the southeastern United States',
                              u'author': u'Osland',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1482',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0050|ecy1625-cit-0050',
                              u'volume': u'19',
                              u'year': u'2013'},
                             {u'DOI': u'10.1371/journal.pone.0099604',
                              u'article-title': u'Aboveground allometric models for freeze-affected black mangroves (Avicennia germinans): equations for a climate sensitive mangrove-marsh ecotone',
                              u'author': u'Osland',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e99604',
                              u'journal-title': u'PLoS ONE',
                              u'key': u'10.1002/ecy.1625-BIB0051|ecy1625-cit-0051',
                              u'volume': u'9',
                              u'year': u'2014'},
                             {u'DOI': u'10.1890/ES15-00042.1',
                              u'article-title': u'Life stage influences the resistance and resilience of black mangrove forests to winter climate extremes',
                              u'author': u'Osland',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'art160',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0052|ecy1625-cit-0052',
                              u'volume': u'6',
                              u'year': u'2015'},
                             {u'DOI': u'10.1111/gcb.13084',
                              u'article-title': u'Beyond just sea-level rise: considering macroclimatic drivers within coastal wetland vulnerability assessments to climate change',
                              u'author': u'Osland',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0053|ecy1625-cit-0053',
                              u'volume': u'22',
                              u'year': u'2016'},
                             {u'DOI': u'10.1146/annurev.ecolsys.37.091305.110100',
                              u'article-title': u'Ecological and evolutionary responses to recent climate change',
                              u'author': u'Parmesan',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'637',
                              u'journal-title': u'Annual Review of Ecology, Evolution, and Systematics',
                              u'key': u'10.1002/ecy.1625-BIB0054|ecy1625-cit-0054',
                              u'volume': u'37',
                              u'year': u'2006'},
                             {u'DOI': u'10.2307/1943020',
                              u'article-title': u'Plant communities in the marshlands of southeastern Louisiana',
                              u'author': u'Penfound',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1',
                              u'journal-title': u'Ecological Monographs',
                              u'key': u'10.1002/ecy.1625-BIB0055|ecy1625-cit-0055',
                              u'volume': u'8',
                              u'year': u'1938'},
                             {u'DOI': u'10.1007/s12237-010-9358-2',
                              u'article-title': u'Temperature tolerance of early life history stages of black mangrove Avicennia germinans: implications for range expansion',
                              u'author': u'Pickens',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'824',
                              u'journal-title': u'Estuaries and Coasts',
                              u'key': u'10.1002/ecy.1625-BIB0056|ecy1625-cit-0056',
                              u'volume': u'34',
                              u'year': u'2011'},
                             {u'DOI': u'10.1038/307321a0',
                              u'article-title': u'The complexity and stability of ecosystems',
                              u'author': u'Pimm',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'321',
                              u'journal-title': u'Nature',
                              u'key': u'10.1002/ecy.1625-BIB0057|ecy1625-cit-0057',
                              u'volume': u'307',
                              u'year': u'1984'},
                             {u'DOI': u'10.1002/ecs2.1268',
                              u'article-title': u'Knocking back invasions: variable resistance and resilience to multiple cold spells in native vs. nonnative fishes',
                              u'author': u'Rehage',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e01268',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0058|ecy1625-cit-0058',
                              u'volume': u'7',
                              u'year': u'2016'},
                             {u'DOI': u'10.1016/j.gecco.2016.07.005',
                              u'article-title': u'Spatio-temporal changes of a mangrove-saltmarsh ecotone in the northeastern coast of Florida, USA',
                              u'author': u'Rodriguez',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'245',
                              u'journal-title': u'Global Ecology and Conservation',
                              u'key': u'10.1002/ecy.1625-BIB0059|ecy1625-cit-0059',
                              u'volume': u'7',
                              u'year': u'2016'},
                             {u'DOI': u'10.1175/1520-0442(1991)004<1103:FCFAPA>2.0.CO;2',
                              u'article-title': u'Florida citrus freezes and polar anticyclones in the Great Plains',
                              u'author': u'Rogers',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1103',
                              u'journal-title': u'Journal of Climate',
                              u'key': u'10.1002/ecy.1625-BIB0060|ecy1625-cit-0060',
                              u'volume': u'4',
                              u'year': u'1991'},
                             {u'DOI': u'10.1111/j.1365-2486.2009.01900.x',
                              u'article-title': u'Chilling damage in a changing climate in coastal landscapes of the subtropical zone: a case study from south Florida',
                              u'author': u'Ross',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1817',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0061|ecy1625-cit-0061',
                              u'volume': u'15',
                              u'year': u'2009'},
                             {u'DOI': u'10.1111/nph.13147',
                              u'article-title': u'Woody plant encroachment of grasslands: a comparison of terrestrial and wetland settings',
                              u'author': u'Saintilan',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1062',
                              u'journal-title': u'New Phytologist',
                              u'key': u'10.1002/ecy.1625-BIB0062|ecy1625-cit-0062',
                              u'volume': u'205',
                              u'year': u'2015'},
                             {u'DOI': u'10.1111/gcb.12341',
                              u'article-title': u'Mangrove expansion and salt marsh decline at\xa0mangrove poleward limits',
                              u'author': u'Saintilan',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'147',
                              u'journal-title': u'Global Change Biology',
                              u'key': u'10.1002/ecy.1625-BIB0063|ecy1625-cit-0063',
                              u'volume': u'20',
                              u'year': u'2014'},
                             {u'DOI': u'10.1007/978-3-642-71745-1',
                              u'author': u'Sakai',
                              u'doi-asserted-by': u'crossref',
                              u'key': u'10.1002/ecy.1625-BIB0064|ecy1625-cit-0064',
                              u'volume-title': u'Frost survival of plants: responses and adaptation to freezing stress',
                              u'year': u'1987'},
                             {u'DOI': u'10.1146/annurev.ecolsys.110308.120317',
                              u'article-title': u'Evolution and ecology of species range limits',
                              u'author': u'Sexton',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'415',
                              u'journal-title': u'Annual Review of Ecology, Evolution, and Systematics',
                              u'key': u'10.1002/ecy.1625-BIB0065|ecy1625-cit-0065',
                              u'volume': u'40',
                              u'year': u'2009'},
                             {u'article-title': u'The distributional history and ecology of mangrove vegetation along the northern Gulf of Mexico coastal region',
                              u'author': u'Sherrod',
                              u'first-page': u'129',
                              u'journal-title': u'Contributions in Marine Science',
                              u'key': u'10.1002/ecy.1625-BIB0066|ecy1625-cit-0066',
                              u'volume': u'28',
                              u'year': u'1985'},
                             {u'DOI': u'10.1111/j.1365-2745.2011.01833.x',
                              u'article-title': u'The ecological role of climate extremes: current understanding and future prospects',
                              u'author': u'Smith',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'651',
                              u'journal-title': u'Journal of Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0067|ecy1625-cit-0067',
                              u'volume': u'99',
                              u'year': u'2011'},
                             {u'DOI': u'10.1890/09-2128.1',
                              u'article-title': u'Controls on resilience and stability in a sediment-subsidized salt marsh',
                              u'author': u'Stagg',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1731',
                              u'journal-title': u'Ecological Applications',
                              u'key': u'10.1002/ecy.1625-BIB0068|ecy1625-cit-0068',
                              u'volume': u'21',
                              u'year': u'2011'},
                             {u'DOI': u'10.1007/s11273-006-0006-3',
                              u'article-title': u'The interplay between mangroves and saltmarshes at the transition between temperate and subtropical climate in Florida',
                              u'author': u'Stevens',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'435',
                              u'journal-title': u'Wetlands Ecology and Management',
                              u'key': u'10.1002/ecy.1625-BIB0069|ecy1625-cit-0069',
                              u'volume': u'14',
                              u'year': u'2006'},
                             {u'DOI': u'10.1002/ecs2.1400',
                              u'article-title': u'Resilience of a tropical sport fish population to a severe cold event varies across five estuaries in southern Florida',
                              u'author': u'Stevens',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e01400',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0070|ecy1625-cit-0070',
                              u'volume': u'7',
                              u'year': u'2016'},
                             {u'DOI': u'10.1111/j.1469-8137.2006.01938.x',
                              u'article-title': u'The role of freezing in setting the latitudinal limits of mangrove forests',
                              u'author': u'Stuart',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'576',
                              u'journal-title': u'New Phytologist',
                              u'key': u'10.1002/ecy.1625-BIB0071|ecy1625-cit-0071',
                              u'volume': u'173',
                              u'year': u'2007'},
                             {u'DOI': u'10.1038/367363a0',
                              u'article-title': u'Biodiversity and stability in grasslands',
                              u'author': u'Tilman',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'363',
                              u'journal-title': u'Nature',
                              u'key': u'10.1002/ecy.1625-BIB0072|ecy1625-cit-0072',
                              u'volume': u'367',
                              u'year': u'1994'},
                             {u'author': u'Tomlinson',
                              u'key': u'10.1002/ecy.1625-BIB0073|ecy1625-cit-0073',
                              u'volume-title': u'The botany of mangroves',
                              u'year': u'1986'},
                             {u'DOI': u'10.1002/9781118412787.ch7',
                              u'author': u'Twilley',
                              u'doi-asserted-by': u'crossref',
                              u'edition': u'2',
                              u'first-page': u'165',
                              u'key': u'10.1002/ecy.1625-BIB0074|ecy1625-cit-0074',
                              u'volume-title': u'Estuarine ecology',
                              u'year': u'2012'},
                             {u'DOI': u'10.1098/rspb.2014.0846',
                              u'article-title': u'The tropicalization of temperate marine ecosystems: climate-mediated changes in herbivory and community phase shifts',
                              u'author': u'Verg\xe9s',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'20140846',
                              u'journal-title': u'Proceedings of the Royal Society B: Biological Sciences',
                              u'key': u'10.1002/ecy.1625-BIB0075|ecy1625-cit-0075',
                              u'volume': u'281',
                              u'year': u'2014'},
                             {u'DOI': u'10.1002/ehs2.1211',
                              u'article-title': u'Impacts of climate change on mangrove ecosystems: a region by region overview',
                              u'author': u'Ward',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e012111',
                              u'journal-title': u'Ecosystem Health and Sustainability',
                              u'key': u'10.1002/ecy.1625-BIB0076|ecy1625-cit-0076',
                              u'volume': u'2',
                              u'year': u'2016'},
                             {u'author': u'West',
                              u'first-page': u'193',
                              u'key': u'10.1002/ecy.1625-BIB0077|ecy1625-cit-0077',
                              u'volume-title': u'Wet coastal ecosystems',
                              u'year': u'1977'},
                             {u'DOI': u'10.1016/S0034-6667(00)00042-7',
                              u'article-title': u'Pollen assemblages as paleoenvironmental proxies in the Florida Everglades',
                              u'author': u'Willard',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'213',
                              u'journal-title': u'Review of Palaeobotany and Palynology',
                              u'key': u'10.1002/ecy.1625-BIB0078|ecy1625-cit-0078',
                              u'volume': u'113',
                              u'year': u'2001'},
                             {u'author': u'Woodward',
                              u'key': u'10.1002/ecy.1625-BIB0079|ecy1625-cit-0079',
                              u'volume-title': u'Climate and plant distribution',
                              u'year': u'1987'},
                             {u'DOI': u'10.1111/1365-2745.12571',
                              u'article-title': u'Salt marsh-mangrove ecotones: using structural gradients to investigate the effects of woody plant encroachment on plant-soil interactions and ecosystem carbon pools',
                              u'author': u'Yando',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'1020',
                              u'journal-title': u'Journal of Ecology',
                              u'key': u'10.1002/ecy.1625-BIB0080|ecy1625-cit-0080',
                              u'volume': u'104',
                              u'year': u'2016'},
                             {u'DOI': u'10.1016/j.yqres.2015.03.005',
                              u'article-title': u'Palynological reconstruction of environmental changes in coastal wetlands of the Florida Everglades since the mid-Holocene',
                              u'author': u'Yao',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'449',
                              u'journal-title': u'Quaternary Research',
                              u'key': u'10.1002/ecy.1625-BIB0081|ecy1625-cit-0081',
                              u'volume': u'83',
                              u'year': u'2015'},
                             {u'DOI': u'10.1002/ecs2.1366',
                              u'article-title': u'Remote sensing of seasonal changes and disturbances in mangrove forest: a case study from South Florida',
                              u'author': u'Zhang',
                              u'doi-asserted-by': u'crossref',
                              u'first-page': u'e01366',
                              u'journal-title': u'Ecosphere',
                              u'key': u'10.1002/ecy.1625-BIB0082|ecy1625-cit-0082',
                              u'volume': u'7',
                              u'year': u'2016'}],
              u'reference-count': 82,
              u'references-count': 82,
              u'relation': {u'cites': []},
              u'score': 1.0,
              u'short-container-title': [u'Ecology'],
              u'short-title': [],
              u'source': u'Crossref',
              u'subject': [u'Ecology, Evolution, Behavior and Systematics'],
              u'subtitle': [],
              u'title': [u'Mangrove expansion and contraction at a poleward range limit: climate extremes and land-ocean temperature gradients'],
              u'type': u'journal-article',
              u'volume': u'98'},
                u'message-type': u'work',
                u'message-version': u'1.0.0',
                u'status': u'ok'}

crossref_200_not_ok = {u'message': None,
                u'message-type': u'work',
                u'message-version': u'1.0.0',
                u'status': u'error'}